### ISSUE TITLE
feature: Add AWS CodeCommit scaffolder support

### ISSUE THREAD

**Issue by stijnbrouwers** [awslabs/backstage-plugins-for-aws#6]
### 🔖 Feature description

This is a duplicate of the following request: https://github.com/awslabs/aws-codeservices-plugins-for-backstage/issues/124
I created the duplicate since the old repository is deprecated and I can no longer comment on that thread.

Add support for [AWS code commit](https://aws.amazon.com/codecommit/) in backstage
* support catalog for git repositories
* 
 

### 🎤 Context

Allow CodeCommit as a source for entities and techdocs. The scaffolder implementation would allow using CodeCommit in the entity templates.

### ✌️ Possible Implementation

# support catalog for git repositories
I don't think this is possible in the form of a plugin, therefore I just contributed the following PR to Backstage that implements this functionality: https://github.com/backstage/backstage/pull/23534

# support template/scaffolder
I guess there are 2 ways:
- Use the AWS SDK to perform the required code commit actions in the scaffolder actions
- Generate username/password and use them to communicate with CodeCommit using the GIT http protocol. I have a working POC to generate these credentials and am willing to contribute. Is there maybe a list of scaffolder actions that are desired to be implemented?

**Comment by niallthomson** [comment]
Hi @stijnbrouwers thanks for raising this issue from the old project.

I'm wondering if we should break this up in to multiple issues, so I want to discuss a little more the various ways we can "support" CodeCommit.

With this new project we have provided an initial implementation of publishing to CodeCommit from the scaffolder.

https://github.com/awslabs/backstage-plugins-for-aws/tree/main/plugins/core/scaffolder-actions/src/actions/codecommit

Documentation is WIP. However, the approach we took uses the AWS API instead of the GIT http protocol and I would be interested to see a POC migrating it to that mechanism since it seems like it would allow us to use more of the upstream Backstage code.

The other main integration I can see is a CatalogProcessor to discover entities from CodeCommit repositories similar to the [AwsS3DiscoveryProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-aws/src/processors/AwsS3DiscoveryProcessor.ts).

As far as TechDocs I haven't worked with integrating it with version control system, only object storage like S3.

**Comment by stijnbrouwers** [comment]
@niallthomson 

Good idea to split it up in multiple tickets.

I will try to have a look at the initial implementation tomorrow and see where I can help out.

Regarding the GIT protocol, this is exactly my thought as well. Using the GIT protocol will make it a lot easier to implement since we can reuse current code, it's less error prone because otherwise we try to kind of "mimic" git behavior using the AWS CLI and it will  be easier collaborate on for anyone else interested.

I will focus tomorrow and next week on creating a small library to retrieve the temporary git credentials to use with the GIT protocol. This way it can be reused with other projects as well. I will let you know when I make some progress on it. 

The Discovery was also on my radar, I don't think it should be that difficult. I just [contributed](https://github.com/backstage/backstage/pull/23543) the code for using CodeCommit as entity provider (here I did use the SDK FYI) and I had a quick peak at discovery. I will try to work on that in the future as well but I think this needs to be done in the Backstage repository just like the CodeCommitIntegration and CodeCommitUrlReader.

The contribution I made also allows to use CodeCommit for storing techdocs and referencing them from another component with the "url:"-syntax.

**Comment by niallthomson** [comment]
I was actually looking at that last month. It did seem like adding an SCM integration required code in upstream Backstage. A UrlReader would be feasible to offload to this project but having them in separate places might not make sense.

**Comment by niallthomson** [comment]
@stijnbrouwers with the break out of discovery to the separate issue would this one now just cover publishing to CodeCommit as a scaffolder action? If so that is already implemented, though I would like to understand whether we can use the GIT protocol instead of our current approach as an improvement.

**Comment by stijnbrouwers** [comment]
@niallthomson yes, this is just the scaffolder action now.

I saw that it's implemented and it looks very sound, I don't know if we have any added value of the GIT protocol at this point.
The idea was re-usability of existing code, but since the action is now already there I'm not sure if there is any added value.
 
We could try implementing an alternative action that does the same publishing action, but uses the GIT protocol. You can then choose which action you want to use, based on the action id. Maybe at some point there will be a need for using the git protocol. But for now, since there is no immediate advantage, it might be overkill...
